language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t gbcgiovanni/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gbcgiovanni/docker-react npm run test
