version: '3'

services: 
    app:
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            context: . # where to find the dockerfile
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
    # app-tests:
    #     environment:
    #         - CHOKIDAR_USEPOLLING=true
    #     build:
    #         context: . # where to find the dockerfile
    #         dockerfile: Dockerfile.dev
    #     volumes: 
    #         - /app/node_modules
    #         - .:/app
    #     command: ["npm", "run", "test"]